version: "3.9"

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=prod
    restart: unless-stopped

  apache:
    build:
      context: ..
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8081:80"
    environment:
      - APP_ENV=prod
    restart: unless-stopped