version: "3.9"

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../gym/var:/var/www/html/var
    environment:
      - APP_ENV=prod

  apache:
    build:
      context: ..
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../gym/var:/var/www/html/var
    container_name: docker-apache
    environment:
      - APP_ENV=prod